name: "Publish to PyPI"
description: "Downloads and publishes the dist tarball to the selected PyPI target, and optionally notifies Slack"

inputs:
  version:
    required: true
    description: "Version string (used to identify the artifact name)"
  pypi_target:
    required: true
    description: "Either 'PyPI Prod' or 'Test PyPI'"
    type: choice
    options: ["PyPI Prod", "Test PyPI"]
  slack_webhook_url:
    required: false
    description: "Optional Slack webhook to notify success"

runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: library-${{ inputs.version }}
        path: dist/
    - name: Publish to PyPI Prod
      if: ${{ inputs.pypi_target == 'PyPI Prod' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
    - name: Publish to TestPyPI
      if: ${{ inputs.pypi_target == 'Test PyPI' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        repository-url: https://test.pypi.org/legacy/
    - name: Notify Slack (success)
      if: ${{ inputs.slack_webhook_url != '' }}
      uses: epic-framework/.github/.github/actions/notify-slack@main
      with:
        message_type: release-done
        webhook_url: ${{ inputs.slack_webhook_url }}
        version: ${{ inputs.version }}
        pypi_target: ${{ inputs.pypi_target }}
